export default function NewsletterPage() {
  return (
    <div className="min-h-screen">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-white mb-2">Plex Newsletter</h1>
          <p className="text-slate-400">
            Monthly updates on what&apos;s been added to the Plex library, generated by Tautulli.
          </p>
        </div>

        <div className="rounded-2xl bg-slate-800/40 border border-slate-700 p-10 text-center">
          <div className="text-4xl mb-3">📬</div>
          <h2 className="text-lg font-semibold text-white mb-2">Newsletters coming soon</h2>
          <p className="text-slate-400 text-sm">
            Tautulli-generated newsletters will be served here once configured.
          </p>
        </div>
      </div>
    </div>
  );
}
